apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.project.notify.svc_name }} # имя сервиса
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.project.svc_port}} # порт, на котором сервис будет принимать трафик
      targetPort: {{ .Values.project.port}} # порт, на который сервис будет перенаправлять трафик
  selector:
    app: {{ .Values.project.notify.name }} # значение метки, по которой селектор будет производить выборку
  type: NodePort # тип сервиса
