apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.env.name}}
data:
  PAYMENT_HOST: {{ .Values.env.PAYMENT_HOST}}
  STOCK_HOST: {{ .Values.env.STOCK_HOST}}
  DELIVERY_HOST: {{ .Values.env.DELIVERY_HOST}}
  NOTIFY_HOST: {{ .Values.env.NOTIFY_HOST}}
  BALANCE_HOST: {{ .Values.env.BALANCE_HOST }}
  DB_HOST: {{ .Values.postgres.host }}
  DB_PORT: {{ .Values.postgres.port | quote}}
  DB_DATABASE: {{ .Values.postgres.name }}