apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.project.notify.name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.project.notify.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.project.notify.name }}
    spec:
      containers:
        - name: {{ .Values.project.notify.container.name }}
          image: {{ .Values.project.notify.container.image }}
          ports:
            - containerPort: {{ .Values.project.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.project.notify.svc_name }} # имя сервиса
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.project.svc_port}} # порт, на котором сервис будет принимать трафик
      targetPort: {{ .Values.project.port}} # порт, на который сервис будет перенаправлять трафик
  selector:
    app: {{ .Values.project.notify.name }} # значение метки, по которой селектор будет производить выборку
  type: NodePort # тип сервиса
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notify-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.project.host }}
      http:
        paths:
          - path: {{ .Values.project.notify.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.project.notify.svc_name}}
                port:
                  number: {{ .Values.project.svc_port }}